apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbit.secretName" . }}
  annotations:
    harness.io/skip-versioning: "true"
type: Opaque
data:
  # echo -n "rabbitmq" | base64
  RABBITMQ_DEFAULT_USER: cmFiYml0bXE=
  # echo -n "123456aA@" | base64
  RABBITMQ_DEFAULT_PASS: MTIzNDU2YUFA