apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
      nodePort: 32261
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
      nodePort: 32262
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
      nodePort: 32263
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
