service: modify-spot-request

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  role: arn:aws:iam::196761233825:role/lambda-ec2-spot-scheduler-role
  environment:
    SPOT_FLEET_REQUEST_ID: sfr-d9b91dfb-b7d4-429b-baee-8b921a8ef298
    ALLOCATION_ID: eipalloc-0f53833ea8ff2874c

functions:
#  modifySpotRequestOn:
#    handler: handler.lambda_handler
#    environment:
#      NEW_TARGET_CAPACITY: 1
#    events:
#      - schedule:
#          rate: cron(0 5 * * ? *)

#  modifySpotRequestOff:
#    handler: handler.lambda_handler
#    environment:
#      NEW_TARGET_CAPACITY: 0
#    events:
#      - schedule:
#          rate: cron(30 14 * * ? *)

  checkSpotInstance:
    handler: assign_eip.check_spot_instance
    events:
      - schedule: rate(5 minutes)
