service: modify-spot-request

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  role: arn:aws:iam::196761233825:role/lambda-ec2-spot-scheduler-role
  environment:
    SPOT_FLEET_REQUEST_ID: sfr-39268480-7edc-4da6-b22d-1480c28a5268
    ALLOCATION_ID: eipalloc-0f53833ea8ff2874c
    DDB_TABLE_NAME: common
    DDB_ITEM_ID: health:jhttp-live
    DDB_FLAG_ITEM_ID: "feature:healthcheck-enabled"
    HEALTHCHECK_URL: "https://jhttp.bluestone.systems/q/health/live"
    UNHEALTHY_RESTART_AFTER_SECONDS: 1860
    HEALTHCHECK_TIMEOUT_SECONDS: 5
    SLACK_POST_URL: "https://slack.bluestone.systems/slack/post-message"
    SLACK_CHANNEL: general-meta-bot-channel
    SLACK_TOKEN: '1235'
    HEALTHCHECK_NOTIFY_WHEN_DISABLED: 'false'

functions:
#  modifySpotRequestOn:
#    handler: handler.lambda_handler
#    environment:
#      NEW_TARGET_CAPACITY: 1
#    events:
#      - schedule:
#          rate: cron(0 5 * * ? *)

#  modifySpotRequestOff:
#    handler: handler.lambda_handler
#    environment:
#      NEW_TARGET_CAPACITY: 0
#    events:
#      - schedule:
#          rate: cron(30 14 * * ? *)

  checkSpotInstance:
    handler: assign_eip.check_spot_instance
    events:
      - schedule: rate(5 minutes)

  healthcheck:
    handler: healthcheck.run
    timeout: 15
    memorySize: 256
    events:
      - schedule: rate(5 minutes)

  toggleHealthcheck:
    handler: toggle_healthcheck.handler
    description: Toggle (enable/disable) the healthcheck feature flag
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /healthcheck/flag
          method: GET
      - httpApi:
          path: /healthcheck/flag
          method: POST
