apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-server.tlsSecretFullName" . }}
  labels:
    {{- include "splunk-server.labels" . | nindent 4 }}
  annotations:
    harness.io/skip-versioning: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.tlsSecret.data.tlsKey | b64enc }}
  tls.crt: {{ .Values.tlsSecret.data.tlsCrt | b64enc }}