pipeline:
  name: meta-pipeline
  identifier: metapipeline
  projectIdentifier: default_project
  orgIdentifier: default
  description: Pipeline to deploy meta application
  tags: {}
  stages:
    - stage:
        name: Configuration
        identifier: Configuration
        description: Prepare configuration for pipeline
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Resolve Configuration
                  identifier: Resolve_Configuration
                  spec:
                    shell: Bash
                    executionTarget: {}
                    delegateSelectors:
                      - helm-delegate
                    source:
                      type: Inline
                      spec:
                        script: |-
                          #!/bin/bash

                          # Lấy giá trị của biến đầu vào từ pipeline
                          project=<+serviceVariables.meta_project_name>
                          echo "Project Name: ${project}"
                          namespace="meta-${project}"
                    environmentVariables: []
                    outputVariables:
                      - name: namespace
                        type: String
                        value: namespace
                    outputAlias:
                      key: configuration
                      scope: Pipeline
                  timeout: 2m
          environment:
            environmentRef: k8ssingleenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8shelmchartinfra
        tags: {}
        timeout: 2m
    - stage:
        name: Deploy
        identifier: Deploy
        description: Rolling Deploy
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: meta
          environment:
            environmentRef: k8ssingleenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8shelmchartinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
