service:
  name: meta
  identifier: meta
  orgIdentifier: default
  projectIdentifier: default_project
  description: Meta service for meta nodejs project
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: meta
            type: HelmChart
            spec:
              store:
                type: Github
                spec:
                  connectorRef: vjcspygitconnector
                  gitFetchType: Branch
                  folderPath: /k8s/app/meta
                  repoName: infra
                  branch: main
              subChartPath: ""
              valuesPaths:
                - k8s/app/meta/values.yaml
              skipResourceVersioning: false
              enableDeclarativeRollback: false
              helmVersion: V3
      variables:
        - name: meta_project_name
          type: String
          default: stock
          description: Yêu cầu phải có branch projects/PROJECT_NAME
          required: true
          value: <+input>.default(stock).allowedValues(stock,binance)
  gitOpsEnabled: false
