services:
  splunk-server:
    image: vjcspy/splunk-server:0.7
    container_name: splunk-server
    ports:
      - "8088:8088" # Splunk management port
      - "8000:8000" # Splunk web interface port
    environment:
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
      - ./splunk-data/splunk:/app/splunk
    # command: tail -f /dev/null
  splunk-license-server:
    image: vjcspy/splunk-license-server:0.2
    container_name: splunk-license-server