services:
  splunk-server:
    image: vjcspy/splunk-server:latest
    container_name: splunk-server
    ports:
      - "8088:8088" # Splunk management port
      - "8000:8000" # Splunk web interface port
    environment:
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
      - ./splunk-data/splunk:/app/splunk
      - ./splunk-data/start.sh:/app/start.sh
    # command: tail -f /dev/null
