services:
  splunk-server:
    image: vjcspy/splunk-server:0.1
    container_name: splunk-server
    ports:
      - "8088:8088" # Splunk management port
      - "8000:8000" # Splunk web interface port
    environment:
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
      - /mnt/existing_ebs_volume/splunk-server/splunk94:/app/splunk
    command: tail -f /dev/null
