apiVersion: v1
kind: Pod
metadata:
  name: temporary-node-pod
  namespace: ggg
spec:
  containers:
    - name: node-container
      image: vjcspy/node:16-yarn-2
      command: [ "/bin/sh", "-c" ]
      args: [ "sleep infinity" ]
      volumeMounts:
        - name: ebs-volume
          mountPath: /mnt_data
  volumes:
    - name: ebs-volume
      hostPath:
        path: /mnt/existing_ebs_volume
  restartPolicy: Never  # Đảm bảo pod chỉ chạy một lần