upstream fastcgi_backend {
  server unix:/sock/phpfpm.sock;
}

server {
  listen 8000;
  server_name _;
  client_max_body_size 64m;

  set $MAGE_ROOT /var/www/html;
  set $fastcgi_backend fastcgi_backend;

  include /var/www/html/nginx.conf.sample;
}
