apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jmeta.fullname" . }}
  labels:
    {{- include "jmeta.labels" . | nindent 4 }}
  annotations:
    redeployTimestamp: "{{ now | unixEpoch }}"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jmeta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jmeta.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jmeta.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: init-copy-config
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - |
              set -e  # Exit on any error
              
              # Define base paths
              BASE_PATH="/host_ebs_volume/jmeta/{{ .Values.projectName }}"
              PROJECT_PATH="$BASE_PATH/projects/{{ .Values.projectName }}"
              QUARKUS_APP_PATH="$PROJECT_PATH/build/quarkus-app"
              CONFIG_DIR="$QUARKUS_APP_PATH/config"
              
              CONFIG_SRC="/host_ebs_volume/credentials/jmeta/{{ .Values.projectName }}/application.properties"
              CONFIG_DEST="$CONFIG_DIR/application.properties"
              
              echo "[Init] Checking for config file at: $CONFIG_SRC"
              
              if [ -f "$CONFIG_SRC" ]; then
                echo "[Init] Config found, copying to: $CONFIG_DEST"
                mkdir -p "$CONFIG_DIR"
                cp "$CONFIG_SRC" "$CONFIG_DEST"
                echo "[Init] Config copied successfully"
                
                # Verify the copy
                if [ -f "$CONFIG_DEST" ]; then
                  echo "[Init] Config verification: OK"
                else
                  echo "[Init] Config verification: FAILED"
                  exit 1
                fi
              else
                echo "[Init] Config file not found, skipping copy operation"
              fi
              
              # Always show directory listing for troubleshooting
              echo "[Init] Listing directories for troubleshooting:"
              echo "[Init] Contents of $QUARKUS_APP_PATH:"
              ls -la "$QUARKUS_APP_PATH" 2>/dev/null || echo "Directory not found"
              echo "[Init] Contents of $CONFIG_DIR:"
              ls -la "$CONFIG_DIR" 2>/dev/null || echo "Directory not found"
              
              echo "[Init] Initialization completed"
          volumeMounts:
            - name: host-volume
              mountPath: /host_ebs_volume

      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: BUILD_TIME
              value: {{ .Values.podEnv.BUILD_TIME }}
            - name: GIT_COMMIT_HASH
              value: {{ .Values.podEnv.GIT_COMMIT_HASH }}
            - name: GIT_COMMIT_MESSAGE
              value: {{ .Values.podEnv.GIT_COMMIT_MESSAGE }}
            - name: GIT_COMMIT_TIME
              value: {{ .Values.podEnv.GIT_COMMIT_TIME }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}