{{- if .Values.rest.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rest
spec:
  replicas: {{ .Values.rest.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: rest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: rest
    spec:
      serviceAccountName: {{ include "supabase.serviceAccountName" . }}
      initContainers:
      {{- if .Values.rest.waitForDb }}
      {{ include "supabase.waitForDb" (include "supabase.dbHost" .) | nindent 6 }}
      {{- end }}
      containers:
        - name: rest
          image: "{{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag }}"
          imagePullPolicy: {{ .Values.rest.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.rest.service.port }}
              name: rest-port
          args:
            - postgrest
          env:
          {{ include "supabase.renderServiceEnv" (list . "rest") | indent 12 }}
          {{- with .Values.rest.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.rest.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
