{{- if .Values.imgproxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-imgproxy
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: imgproxy
spec:
  replicas: {{ .Values.imgproxy.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: imgproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: imgproxy
    spec:
      serviceAccountName: {{ include "supabase.serviceAccountName" . }}
      initContainers:
      {{ include "supabase.waitForDeployment" (list . "supabase-postgres") | nindent 8 }}
      containers:
        - name: imgproxy
          image: "{{ .Values.imgproxy.image.repository }}:{{ .Values.imgproxy.image.tag }}"
          imagePullPolicy: {{ .Values.imgproxy.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.imgproxy.service.port }}
              name: imgproxy-port
          env:
          {{ include "supabase.renderServiceEnv" (list . "imgproxy") | indent 12 }}
          volumeMounts:
            - name: supabase-root
              mountPath: /var/lib/storage
              subPath: storage
          {{- with .Values.imgproxy.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.imgproxy.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: supabase-root
          hostPath:
            path: /mnt/ebs_postgres_data/supabase/volumes
            type: Directory
{{- end }}
