{{- if .Values.meta.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-meta
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: meta
spec:
  replicas: {{ .Values.meta.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: meta
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: meta
    spec:
      serviceAccountName: {{ include "supabase.serviceAccountName" . }}
      initContainers:
{{ include "supabase.waitForDeployment" (list . "supabase-analytics") | nindent 6 }}
      containers:
        - name: meta
          image: "{{ .Values.meta.image.repository }}:{{ .Values.meta.image.tag }}"
          imagePullPolicy: {{ .Values.meta.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.meta.service.port }}
              name: meta-port
          env:
          {{ include "supabase.renderServiceEnv" (list . "meta") | indent 12 }}
{{- end }}
