{{- if .Values.functions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-functions
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: functions
spec:
  replicas: {{ .Values.functions.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: functions
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: functions
    spec:
      serviceAccountName: {{ include "supabase.serviceAccountName" . }}
      initContainers:
        - name: init-ebs-check
          image: busybox:1.37.0
          command: [ "sh","-c","for i in $(seq 1 5); do echo Checking EBS mount attempt $i; if [ -f /host_ebs_volume/DONT_DELETE ]; then echo OK; exit 0; fi; sleep 10; done; echo FAIL; exit 1" ]
          volumeMounts:
            - name: host-ebs-root
              mountPath: /host_ebs_volume
      containers:
        - name: functions
          image: "{{ .Values.functions.image.repository }}:{{ .Values.functions.image.tag }}"
          imagePullPolicy: {{ .Values.functions.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.functions.service.port }}
              name: functions-port
          args:
            - start
            - --main-service
            - /home/deno/functions/main
          env:
          {{ include "supabase.renderServiceEnv" (list . "functions") | indent 12 }}
          volumeMounts:
            - name: supabase-root
              mountPath: /home/deno/functions
              subPath: functions
          {{- with .Values.functions.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.functions.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: host-ebs-root
          hostPath:
            path: /mnt/existing_ebs_volume
            type: Directory
        - name: supabase-root
          hostPath:
            path: /mnt/existing_ebs_volume/supabase/volumes
            type: Directory
{{- end }}
