{{- if .Values.supavisor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supavisor
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: supavisor
spec:
  replicas: {{ .Values.supavisor.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: supavisor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: supavisor
    spec:
      serviceAccountName: {{ include "supabase.serviceAccountName" . }}
      initContainers:
{{ include "supabase.waitForDeployment" (list . "supabase-analytics") | nindent 6 }}
      containers:
        - name: supavisor
          image: "{{ .Values.supavisor.image.repository }}:{{ .Values.supavisor.image.tag }}"
          imagePullPolicy: {{ .Values.supavisor.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres-port
            - containerPort: {{ .Values.supavisor.service.port }}
              name: pooler-port
          command:
            - /bin/sh
            - -c
            - >
              /app/bin/migrate && /app/bin/supavisor eval "$(cat /etc/pooler/pooler.exs)" && /app/bin/server
          env:
          {{ include "supabase.renderServiceEnv" (list . "supavisor") | indent 12 }}
          volumeMounts:
            - name: supabase-root
              mountPath: /etc/pooler/pooler.exs
              subPath: pooler/pooler.exs
              readOnly: true
          {{- with .Values.supavisor.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.supavisor.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: supabase-root
          hostPath:
            path: /mnt/ebs_postgres_data/supabase/volumes
            type: Directory
{{- end }}
