{{- /* Kong Ingress */ -}}
{{- if and .Values.kong.enabled .Values.ingress.kong.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supabase-kong
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.ingress.kong.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.kong.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: {{ .Values.kong.service.ports.http }}
---
{{- end }}

{{- /* Studio Ingress */ -}}
{{- if .Values.ingress.studio.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supabase-studio
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.ingress.studio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.studio.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supabase-studio
                port:
                  number: {{ .Values.studio.service.port }}
{{- end }}
