{{- if .Values.functions.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-functions
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: functions
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: functions
  ports:
    - name: http
      port: {{ .Values.functions.service.port }}
      targetPort: {{ .Values.functions.service.port }}
{{- end }}
