{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-storage
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
  ports:
    - name: http
      port: {{ .Values.storage.service.port }}
      targetPort: {{ .Values.storage.service.port }}
{{- end }}
