{{- if .Values.supavisor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supavisor
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: supavisor
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: supavisor
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
      nodePort: 32362
    - name: pooler-port
      port: {{ .Values.supavisor.service.port }}
      targetPort: {{ .Values.supavisor.service.port }}
      nodePort: 32363
{{- end }}
