{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
  ports:
    - name: http
      port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.port }}
{{- end }}
