{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-analytics
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: analytics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: analytics
  ports:
    - name: http
      port: {{ .Values.analytics.service.port }}
      targetPort: {{ .Values.analytics.service.port }}
{{- end }}
