{{- if .Values.meta.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-meta
  labels:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: meta
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: meta
  ports:
    - name: http
      port: {{ .Values.meta.service.port }}
      targetPort: {{ .Values.meta.service.port }}
{{- end }}
