{{- /* Postgres Service - Internal */ -}}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-postgres
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- /* Auth Service - Internal */ -}}
{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-auth
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.port }}
      protocol: TCP
      name: auth-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* PostgREST Service - Internal */ -}}
{{- if .Values.rest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rest.service.port }}
      targetPort: {{ .Values.rest.service.port }}
      protocol: TCP
      name: rest-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Realtime Service - Internal */ -}}
{{- if .Values.realtime.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-realtime
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.realtime.service.port }}
      targetPort: {{ .Values.realtime.service.port }}
      protocol: TCP
      name: realtime-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Storage API Service - Internal */ -}}
{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-storage
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.storage.service.port }}
      targetPort: {{ .Values.storage.service.port }}
      protocol: TCP
      name: storage-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Imgproxy Service - Internal */ -}}
{{- if .Values.imgproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-imgproxy
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.imgproxy.service.port }}
      targetPort: {{ .Values.imgproxy.service.port }}
      protocol: TCP
      name: imgproxy-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Meta Service - Internal */ -}}
{{- if .Values.meta.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-meta
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.meta.service.port }}
      targetPort: {{ .Values.meta.service.port }}
      protocol: TCP
      name: meta-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Functions Service - Internal */ -}}
{{- if .Values.functions.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-functions
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.functions.service.port }}
      targetPort: {{ .Values.functions.service.port }}
      protocol: TCP
      name: functions-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Studio Service - Internal */ -}}
{{- if .Values.studio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.studio.service.port }}
      targetPort: {{ .Values.studio.service.port }}
      protocol: TCP
      name: studio-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Analytics Service - Exposed in docker-compose */ -}}
{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-analytics
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.analytics.service.port }}
      targetPort: {{ .Values.analytics.service.port }}
      protocol: TCP
      name: analytics-port
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Kong Service - Exposed in docker-compose */ -}}
{{- if .Values.kong.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-kong
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kong.service.ports.http }}
      targetPort: {{ .Values.kong.service.ports.http }}
      protocol: TCP
      name: kong-http
    - port: {{ .Values.kong.service.ports.https }}
      targetPort: {{ .Values.kong.service.ports.https }}
      protocol: TCP
      name: kong-https
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}

{{- /* Supavisor Service - Exposed in docker-compose with 2 ports */ -}}
{{- if .Values.supavisor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: supabase-supavisor
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
    - port: {{ .Values.supavisor.service.port }}
      targetPort: {{ .Values.supavisor.service.port }}
      protocol: TCP
      name: pooler
  selector:
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}
