{{- if not (lookup "v1" "Secret" .Release.Namespace (include "ggg-api.tlsSecretFullName" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ggg-api.tlsSecretFullName" . }}
  labels:
    {{- include "ggg-api.labels" . | nindent 4 }}
  annotations:
    harness.io/skip-versioning: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.tlsSecret.data.tlsKey | b64enc }}
  tls.crt: {{ .Values.tlsSecret.data.tlsCrt | b64enc }}
{{- end }}
